### PR TITLE
Follow unfollow

### PR DESCRIPTION
**Pull request by Lukan707**
Not quite finished, as there still are some warnings, and following and unfollowing functioanlity are not yet implemented.

The reason for this pull request is due to testing, only possible in production (yay, that is quality).

### CODE REVIEW

**Review by AlbinoLoaf — APPROVED** [review]
We did a good job  <3

**Review by SkarpKat — COMMENTED** [review]
There is something wrong. A lot of files have been changed with it's self. Do you know what happened?

**Comment by Lukan707** [comment]
> There is something wrong. A lot of files have been changed with it's self. Do you know what happened?

I am not entirely sure. It has seemed to occur at this commit 75e0ad55676a894d8b80b18dc1ca5de65ff062e5, where I believe Marius have added som comments with links to sources.

**Comment by Lukan707** [comment]
> > There is something wrong. A lot of files have been changed with it's self. Do you know what happened?
> 
> I am not entirely sure. It has seemed to occur at this commit [75e0ad5](https://github.com/ITU-BDSA23-GROUP4/Chirp/commit/75e0ad55676a894d8b80b18dc1ca5de65ff062e5), where I believe Marius have added som comments with links to sources.
> 
> I will see if I can revert it, or bring the changes to a new branch without the commit, and create a new pull request.

I can see this is due to windows using CFLF for linebreaks and Linux using only LF control characters for linebreaks, which causes git to view every line as modified.

https://stackoverflow.com/questions/5787937/git-status-shows-files-as-changed-even-though-contents-are-the-same

**Comment by Lukan707** [comment]
> > > There is something wrong. A lot of files have been changed with it's self. Do you know what happened?
> > 
> > 
> > I am not entirely sure. It has seemed to occur at this commit [75e0ad5](https://github.com/ITU-BDSA23-GROUP4/Chirp/commit/75e0ad55676a894d8b80b18dc1ca5de65ff062e5), where I believe Marius have added som comments with links to sources.
> > I will see if I can revert it, or bring the changes to a new branch without the commit, and create a new pull request.
> 
> I can see this is due to windows using CFLF for linebreaks and Linux using only LF control characters for linebreaks, which causes git to view every line as modified.
> 
> https://stackoverflow.com/questions/5787937/git-status-shows-files-as-changed-even-though-contents-are-the-same
> 
> To prevent this in the future, we all need to set a git configuration to either convert automatically to crlf (windows style) or lf (unix style). An issue has been raised, reagarding this.
> 
> https://stackoverflow.com/questions/10418975/how-to-change-line-ending-settings

**Review by SkarpKat — CHANGES_REQUESTED** [review]
Looks good

**Review by SkarpKat — APPROVED** [review]

**Comment by Lukan707** [comment]
Missing migrations. 
Should first be merged into main when:
1. Migrations on main have been fixed
2. Theese changes is merged into this branch
3. New migrations is applied to this branch

**Comment by Lukan707** [comment]
> Missing migrations. Should first be merged into main when:
> 
> 1. Migrations on main have been fixed
> 2. Theese changes is merged into this branch
> 3. New migrations is applied to this branch

- Migrations have now been added.
- Unit tests have been added.
- Logic to razor pages have been added.

Please re-review this pull request.

**Pull request merged**
